### ISSUE TITLE
Event logging of matched regexes

### ISSUE THREAD

**Issue by NSkelsey** [Taipo/pareto_security#1]
Hi @Taipo do you do any logging or notification when the plugin detects and drops malicious strings?

**Comment by Taipo** [comment]
The original incarnation of this plugin did have notifications but I removed it.

**Comment by Taipo** [comment]
I think it'd be beneficial to have some form of generic log of malicious requests where the log entries are brief, logging just the malicious content rather than the entire request, i.e especially with _POST

**Comment by NSkelsey** [comment]
I agree. There is a lot of value in knowing that you have been plonked. Maybe it is not even worth a list, but a running summary and a moving average :)

**Comment by Taipo** [comment]
By far the majority of attack strings are quite uninteresting and repetitive - logging only the truly interesting stuff might be an option.

**Comment by Taipo** [comment]
Added. Now has a lasted 100 attacks log.

**Comment by Taipo** [comment]
Also now emails out High Severity attacks.
